# Generated by Django 4.2.6 on 2023-10-19 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Noticias',
        ),
    ]
