# Generated by Django 4.2.6 on 2023-10-25 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Noticias',
        ),
    ]
