# Generated by Django 4.2.6 on 2023-10-28 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0012_usuario_delete_perfil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
