# Generated by Django 4.2.6 on 2023-10-28 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_rename_teste_usuario_texto'),
        ('noticias', '0013_delete_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
        ),
    ]
