# Generated by Django 4.2.6 on 2023-10-28 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0015_alter_noticias_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Noticias',
        ),
    ]
