# Generated by Django 4.2.6 on 2023-10-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0017_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='atualizado',
            field=models.BooleanField(default=False),
        ),
    ]
