# Generated by Django 4.2.6 on 2023-10-28 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_userprofile_delete_usuario'),
        ('noticias', '0018_noticias_atualizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='user_profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.userprofile'),
        ),
    ]
