# Generated by Django 4.2.6 on 2023-10-28 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0020_alter_noticias_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticias',
            name='user_profile',
        ),
    ]
