# Generated by Django 4.2.7 on 2023-12-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0021_remove_noticias_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='curtida',
            field=models.IntegerField(default=0),
        ),
    ]
