# Generated by Django 5.0 on 2024-01-18 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0022_noticias_curtida'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticias',
            name='curtida',
        ),
        migrations.AlterField(
            model_name='noticias',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticias_autor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='noticias',
            name='curtida',
            field=models.ManyToManyField(related_name='noticias_curtidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
