# Generated by Django 4.2.6 on 2023-10-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('notice', models.TextField(default='Digite aqui')),
            ],
        ),
        migrations.AddField(
            model_name='tipos',
            name='valor',
            field=models.FloatField(default=1),
        ),
    ]
