# Generated by Django 4.2.6 on 2023-10-19 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_noticias_tipos_valor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Noticias',
        ),
    ]
