# Generated by Django 4.2.6 on 2023-10-28 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_delete_noticias'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tipos',
        ),
    ]
