# Generated by Django 4.2.6 on 2023-10-28 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='teste',
            new_name='texto',
        ),
    ]
